// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package nodecomm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeCommServiceClient is the client API for NodeCommService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeCommServiceClient interface {
	KeepAlive(ctx context.Context, in *NodeMessage, opts ...grpc.CallOption) (*NodeMessage, error)
	SendMessage(ctx context.Context, in *NodeMessage, opts ...grpc.CallOption) (*NodeMessage, error)
	SendCoordinationMessage(ctx context.Context, in *CoordinationMessage, opts ...grpc.CallOption) (*CoordinationMessage, error)
	Shutdown(ctx context.Context, in *ControlMessage, opts ...grpc.CallOption) (*ControlMessage, error)
	SendControlMessage(ctx context.Context, in *ControlMessage, opts ...grpc.CallOption) (*ControlMessage, error)
	SendClientMessage(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ClientMessage, error)
	SendServerMessage(ctx context.Context, in *ServerMessage, opts ...grpc.CallOption) (*ClientMessage, error)
	// Events are published from Server to Client
	SendEventMessage(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*EventMessage, error)
	// Client asks for a file in Read-Mode
	RequestReadFile(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (NodeCommService_RequestReadFileClient, error)
	// Client asks to write to a file
	RequestWriteFile(ctx context.Context, opts ...grpc.CallOption) (NodeCommService_RequestWriteFileClient, error)
}

type nodeCommServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeCommServiceClient(cc grpc.ClientConnInterface) NodeCommServiceClient {
	return &nodeCommServiceClient{cc}
}

func (c *nodeCommServiceClient) KeepAlive(ctx context.Context, in *NodeMessage, opts ...grpc.CallOption) (*NodeMessage, error) {
	out := new(NodeMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) SendMessage(ctx context.Context, in *NodeMessage, opts ...grpc.CallOption) (*NodeMessage, error) {
	out := new(NodeMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) SendCoordinationMessage(ctx context.Context, in *CoordinationMessage, opts ...grpc.CallOption) (*CoordinationMessage, error) {
	out := new(CoordinationMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/SendCoordinationMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) Shutdown(ctx context.Context, in *ControlMessage, opts ...grpc.CallOption) (*ControlMessage, error) {
	out := new(ControlMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) SendControlMessage(ctx context.Context, in *ControlMessage, opts ...grpc.CallOption) (*ControlMessage, error) {
	out := new(ControlMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/SendControlMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) SendClientMessage(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (*ClientMessage, error) {
	out := new(ClientMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/SendClientMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) SendServerMessage(ctx context.Context, in *ServerMessage, opts ...grpc.CallOption) (*ClientMessage, error) {
	out := new(ClientMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/SendServerMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) SendEventMessage(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*EventMessage, error) {
	out := new(EventMessage)
	err := c.cc.Invoke(ctx, "/NodeComm.NodeCommService/SendEventMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeCommServiceClient) RequestReadFile(ctx context.Context, in *ClientMessage, opts ...grpc.CallOption) (NodeCommService_RequestReadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeCommService_ServiceDesc.Streams[0], "/NodeComm.NodeCommService/RequestReadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeCommServiceRequestReadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeCommService_RequestReadFileClient interface {
	Recv() (*FileBodyMessage, error)
	grpc.ClientStream
}

type nodeCommServiceRequestReadFileClient struct {
	grpc.ClientStream
}

func (x *nodeCommServiceRequestReadFileClient) Recv() (*FileBodyMessage, error) {
	m := new(FileBodyMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeCommServiceClient) RequestWriteFile(ctx context.Context, opts ...grpc.CallOption) (NodeCommService_RequestWriteFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &NodeCommService_ServiceDesc.Streams[1], "/NodeComm.NodeCommService/RequestWriteFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeCommServiceRequestWriteFileClient{stream}
	return x, nil
}

type NodeCommService_RequestWriteFileClient interface {
	Send(*ClientMessage) error
	CloseAndRecv() (*ClientMessage, error)
	grpc.ClientStream
}

type nodeCommServiceRequestWriteFileClient struct {
	grpc.ClientStream
}

func (x *nodeCommServiceRequestWriteFileClient) Send(m *ClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeCommServiceRequestWriteFileClient) CloseAndRecv() (*ClientMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeCommServiceServer is the server API for NodeCommService service.
// All implementations must embed UnimplementedNodeCommServiceServer
// for forward compatibility
type NodeCommServiceServer interface {
	KeepAlive(context.Context, *NodeMessage) (*NodeMessage, error)
	SendMessage(context.Context, *NodeMessage) (*NodeMessage, error)
	SendCoordinationMessage(context.Context, *CoordinationMessage) (*CoordinationMessage, error)
	Shutdown(context.Context, *ControlMessage) (*ControlMessage, error)
	SendControlMessage(context.Context, *ControlMessage) (*ControlMessage, error)
	SendClientMessage(context.Context, *ClientMessage) (*ClientMessage, error)
	SendServerMessage(context.Context, *ServerMessage) (*ClientMessage, error)
	// Events are published from Server to Client
	SendEventMessage(context.Context, *EventMessage) (*EventMessage, error)
	// Client asks for a file in Read-Mode
	RequestReadFile(*ClientMessage, NodeCommService_RequestReadFileServer) error
	// Client asks to write to a file
	RequestWriteFile(NodeCommService_RequestWriteFileServer) error
	mustEmbedUnimplementedNodeCommServiceServer()
}

// UnimplementedNodeCommServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeCommServiceServer struct {
}

func (UnimplementedNodeCommServiceServer) KeepAlive(context.Context, *NodeMessage) (*NodeMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedNodeCommServiceServer) SendMessage(context.Context, *NodeMessage) (*NodeMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedNodeCommServiceServer) SendCoordinationMessage(context.Context, *CoordinationMessage) (*CoordinationMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCoordinationMessage not implemented")
}
func (UnimplementedNodeCommServiceServer) Shutdown(context.Context, *ControlMessage) (*ControlMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedNodeCommServiceServer) SendControlMessage(context.Context, *ControlMessage) (*ControlMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendControlMessage not implemented")
}
func (UnimplementedNodeCommServiceServer) SendClientMessage(context.Context, *ClientMessage) (*ClientMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendClientMessage not implemented")
}
func (UnimplementedNodeCommServiceServer) SendServerMessage(context.Context, *ServerMessage) (*ClientMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendServerMessage not implemented")
}
func (UnimplementedNodeCommServiceServer) SendEventMessage(context.Context, *EventMessage) (*EventMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEventMessage not implemented")
}
func (UnimplementedNodeCommServiceServer) RequestReadFile(*ClientMessage, NodeCommService_RequestReadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestReadFile not implemented")
}
func (UnimplementedNodeCommServiceServer) RequestWriteFile(NodeCommService_RequestWriteFileServer) error {
	return status.Errorf(codes.Unimplemented, "method RequestWriteFile not implemented")
}
func (UnimplementedNodeCommServiceServer) mustEmbedUnimplementedNodeCommServiceServer() {}

// UnsafeNodeCommServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeCommServiceServer will
// result in compilation errors.
type UnsafeNodeCommServiceServer interface {
	mustEmbedUnimplementedNodeCommServiceServer()
}

func RegisterNodeCommServiceServer(s grpc.ServiceRegistrar, srv NodeCommServiceServer) {
	s.RegisterService(&NodeCommService_ServiceDesc, srv)
}

func _NodeCommService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).KeepAlive(ctx, req.(*NodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).SendMessage(ctx, req.(*NodeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_SendCoordinationMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinationMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).SendCoordinationMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/SendCoordinationMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).SendCoordinationMessage(ctx, req.(*CoordinationMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).Shutdown(ctx, req.(*ControlMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_SendControlMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).SendControlMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/SendControlMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).SendControlMessage(ctx, req.(*ControlMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_SendClientMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).SendClientMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/SendClientMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).SendClientMessage(ctx, req.(*ClientMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_SendServerMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).SendServerMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/SendServerMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).SendServerMessage(ctx, req.(*ServerMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_SendEventMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeCommServiceServer).SendEventMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeComm.NodeCommService/SendEventMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeCommServiceServer).SendEventMessage(ctx, req.(*EventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeCommService_RequestReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeCommServiceServer).RequestReadFile(m, &nodeCommServiceRequestReadFileServer{stream})
}

type NodeCommService_RequestReadFileServer interface {
	Send(*FileBodyMessage) error
	grpc.ServerStream
}

type nodeCommServiceRequestReadFileServer struct {
	grpc.ServerStream
}

func (x *nodeCommServiceRequestReadFileServer) Send(m *FileBodyMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeCommService_RequestWriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeCommServiceServer).RequestWriteFile(&nodeCommServiceRequestWriteFileServer{stream})
}

type NodeCommService_RequestWriteFileServer interface {
	SendAndClose(*ClientMessage) error
	Recv() (*ClientMessage, error)
	grpc.ServerStream
}

type nodeCommServiceRequestWriteFileServer struct {
	grpc.ServerStream
}

func (x *nodeCommServiceRequestWriteFileServer) SendAndClose(m *ClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeCommServiceRequestWriteFileServer) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeCommService_ServiceDesc is the grpc.ServiceDesc for NodeCommService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeCommService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeComm.NodeCommService",
	HandlerType: (*NodeCommServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeepAlive",
			Handler:    _NodeCommService_KeepAlive_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _NodeCommService_SendMessage_Handler,
		},
		{
			MethodName: "SendCoordinationMessage",
			Handler:    _NodeCommService_SendCoordinationMessage_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _NodeCommService_Shutdown_Handler,
		},
		{
			MethodName: "SendControlMessage",
			Handler:    _NodeCommService_SendControlMessage_Handler,
		},
		{
			MethodName: "SendClientMessage",
			Handler:    _NodeCommService_SendClientMessage_Handler,
		},
		{
			MethodName: "SendServerMessage",
			Handler:    _NodeCommService_SendServerMessage_Handler,
		},
		{
			MethodName: "SendEventMessage",
			Handler:    _NodeCommService_SendEventMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestReadFile",
			Handler:       _NodeCommService_RequestReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RequestWriteFile",
			Handler:       _NodeCommService_RequestWriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "NodeComm.proto",
}
